version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .

     # deploy the image
     - run: |         
         docker login --username=$APP_USERNAME --password=$APP_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$APP_NAME/web
         docker push registry.heroku.com/$APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $APP_NAME
